name: Environment variable Step-Level

on: 
  push

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps: 
      - name: Docker Build
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: nabz1097
          IMAGE_NAME: github-actions-nginx
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env: 
          DOCKER_PASSWORD: password97
          DOCKER_USERNAME: nabz1097
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        env: 
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: 
          IMAGE_NAME: github-actions-nginx
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest